-- ============================================================
-- Mysterious — visitor analytics migration
-- HOW TO RUN: Supabase dashboard -> your "mysterious" project ->
--   SQL Editor -> New query -> paste this ENTIRE file -> Run.
-- Safe to run more than once (IF NOT EXISTS).
-- One row per visitor per day (session_key = hash of IP + UA + date).
-- ============================================================

CREATE TABLE IF NOT EXISTS visits(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_key TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  last_seen_at TIMESTAMPTZ DEFAULT now(),
  page_views INTEGER DEFAULT 1,
  entry_page TEXT DEFAULT '',
  last_page TEXT DEFAULT '',
  country TEXT DEFAULT '',
  timezone TEXT DEFAULT '',
  device TEXT DEFAULT '',
  user_id BIGINT
);

CREATE INDEX IF NOT EXISTS visits_last_seen_idx ON visits(last_seen_at DESC);
CREATE INDEX IF NOT EXISTS visits_created_idx ON visits(created_at DESC);

-- Verify: SELECT count(*) FROM visits;
