// netlify/functions/api.js — ONE catch-all Netlify Function for the Mysterious API.
//
// It adapts Netlify Function events to the existing Vercel-style handlers in
// ../../api/ (module.exports = async function handler(req, res)), so the 37
// handlers are reused unchanged.
//
// netlify.toml rewrites /api/* -> /.netlify/functions/api/:splat (status 200),
// so this function sees event.path like "/.netlify/functions/api/notes/abc".
// The route table is generated by scanning api/**/*.js:
//   api/notes/index.js        -> /api/notes
//   api/notes/[slug].js       -> /api/notes/:slug
//   api/notes/[slug]/read.js  -> /api/notes/:slug/read
// Path params are merged into req.query (same as Vercel).

const fs = require('fs');
const path = require('path');

const API_DIR = path.join(__dirname, '..', '..', 'api');

// ---------- route table (built once at cold start) ----------
function buildRoutes() {
  const routes = [];
  (function walk(dir, segs) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { walk(p, segs.concat(e.name)); continue; }
      if (!e.name.endsWith('.js')) continue;
      let s = segs.concat(e.name.replace(/\.js$/, ''));
      if (s[s.length - 1] === 'index') s = s.slice(0, -1); // index.js -> parent path
      const pattern = s.map((x) =>
        x.startsWith('[') && x.endsWith(']') ? ':' + x.slice(1, -1) : x
      );
      routes.push({ pattern, file: p });
    }
  })(API_DIR, []);
  // Most-specific first: more segments, then fewer dynamic segments.
  routes.sort((a, b) => {
    if (b.pattern.length !== a.pattern.length) return b.pattern.length - a.pattern.length;
    const da = a.pattern.filter((x) => x[0] === ':').length;
    const db = b.pattern.filter((x) => x[0] === ':').length;
    return da - db;
  });
  return routes;
}
const ROUTES = buildRoutes();

function matchRoute(segs) {
  for (const r of ROUTES) {
    if (r.pattern.length !== segs.length) continue;
    const params = {};
    let ok = true;
    for (let i = 0; i < r.pattern.length; i++) {
      const p = r.pattern[i];
      if (p[0] === ':') {
        params[p.slice(1)] = decodeURIComponent(segs[i]);
      } else if (p !== segs[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return { file: r.file, params };
  }
  return null;
}

// ---------- Netlify event -> Vercel-style req ----------
function toReq(event, params) {
  const headers = {};
  for (const k of Object.keys(event.headers || {})) {
    headers[k.toLowerCase()] = event.headers[k];
  }
  let body = null;
  if (event.body) {
    const raw = event.isBase64Encoded
      ? Buffer.from(event.body, 'base64').toString('utf8')
      : event.body;
    const ct = headers['content-type'] || '';
    const t = raw.trim();
    if (ct.indexOf('application/json') !== -1 || t[0] === '{' || t[0] === '[') {
      try { body = JSON.parse(raw); } catch (e) { body = null; }
    } else {
      body = raw;
    }
  }
  return {
    method: event.httpMethod,
    query: Object.assign({}, event.queryStringParameters || {}, params),
    body,
    headers,
  };
}

// ---------- Vercel-style res mock -> Netlify response ----------
function makeRes() {
  const headers = {};
  const multi = {};
  return {
    statusCode: 200,
    _headers: headers,
    _multi: multi,
    body: '',
    setHeader(k, v) {
      const key = String(k);
      if (key.toLowerCase() === 'set-cookie') {
        (multi[key] = multi[key] || []).push(String(v));
      } else {
        headers[key] = String(v);
      }
    },
    getHeader(k) { return headers[String(k)]; },
    end(b) { this.body = b == null ? '' : String(b); },
  };
}

function notFound() {
  return {
    statusCode: 404,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ error: 'not found' }),
  };
}

exports.handler = async (event, context) => {
  try {
    let p = event.path || '';
    const prefix = '/.netlify/functions/api';
    if (p.indexOf(prefix) === 0) p = p.slice(prefix.length);
    p = p.replace(/^\/+|\/+$/g, '');
    const segs = p ? p.split('/') : [];

    const m = matchRoute(segs);
    if (!m) return notFound();

    const handler = require(m.file);
    const req = toReq(event, m.params);
    const res = makeRes();
    await handler(req, res);

    const out = {
      statusCode: res.statusCode || 200,
      headers: res._headers,
      body: res.body,
    };
    if (Object.keys(res._multi).length) out.multiValueHeaders = res._multi;
    return out;
  } catch (e) {
    console.error('netlify api adapter error:', e && e.message);
    return {
      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'server error' }),
    };
  }
};

// Exported for the local test harness.
exports.__test__ = { ROUTES, matchRoute, toReq, makeRes };
